service: conector-api

image: wchampionjohn/conector-api-web
ssh:
  user: "ec2-user"
servers:
  job:
    hosts:
      - staging_io
    cmd: bundle exec sidekiq -q default -q low -q critical -q unsafe
    proxy: false
  web:
    hosts:
      - staging_io  # from ssh config
    proxy: false
    labels:
      kamal.role: web

registry:
  server: ghcr.io
  username: wchampionjohn
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - LOOKR_API_URL
    - INTERNAL_KABOB_PLATFORM_URL
    - APPIER_DSP_ENDPOINT
    - APPIER_API_KEY
    - TTD_DSP_ENDPOINT
    - TTD_API_KEY
    - LOOKR_API_URL
    - CONNECTOR_API_URL
    - REDIS_URL
  clear:
    SOLID_QUEUE_IN_PUMA: true
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "conector_storage:/rails/storage"

builder:
  arch: amd64
accessories:
  db:
    image: postgres:16
    host: staging_io
    env:
      clear:
        POSTGRES_USER: 'kk1234'
        POSTGRES_DB: 'conector_production'
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    host: staging_io
    directories:
      - data:/data
deploy_timeout: 20
