service: conector-api

image: wchampionjohn/conector-api-web
ssh:
  user: deploy
servers:
  web:
    hosts:
      - 34.80.69.176
    options:
      network: 'conector'
  job:
    hosts:
      - 34.80.69.176
    cmd: bundle exec sidekiq -q default -q low -q critical -q unsafe
    options:
      network: 'conector'
registry:
  server: ghcr.io
  username: wchampionjohn
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
  clear:
    SOLID_QUEUE_IN_PUMA: true
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "conector_storage:/rails/storage"

builder:
  arch: amd64
accessories:
  db:
    image: postgres:16
    host: 34.80.69.176
    env:
      clear:
        POSTGRES_USER: 'kk1234'
        POSTGRES_DB: 'conector_production'
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
    options:
      network: 'conector'

  redis:
    image: redis:7.0
    host: 34.80.69.176
    directories:
      - data:/data
    options:
      network: 'conector'
deploy_timeout: 10
