class AdSpace < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  belongs_to :publisher

  has_many :ad_units
  has_many :deals

  # validations ...............................................................
  validates :name, presence: true
  validates :ad_format, presence: true
  validates :floor_price, numericality: { greater_than_or_equal_to: 0 }, allow_nil: true
  # callbacks .................................................................
  # scopes ....................................................................
  scope :active, -> { where(is_active: true, status: "active") }
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
