# == Schema Information
#
# Table name: content_taxonomies(from IAB Content Taxonomies)
#
#  id            :bigint           not null, primary key
#  name          :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  iab_unique_id :string
#
# Indexes
#
#  index_content_taxonomies_on_iab_unique_id  (iab_unique_id) UNIQUE
#
class ContentTaxonomy < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  has_many :ad_space_content_taxonomies
  has_many :ad_spaces, through: :ad_space_content_taxonomies
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
