# == Schema Information
#
# Table name: device_layouts
#
#  id                      :bigint           not null, primary key
#  height                  :integer
#  width                   :integer
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  device_id(關聯的裝置ID) :bigint
#
class DeviceLayout < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  belongs_to :device
  has_many :device_layout_blocks
  # validations ...............................................................
  validates :width, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :height, presence: true, numericality: { only_integer: true, greater_than: 0 }
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  accepts_nested_attributes_for :device_layout_blocks, allow_destroy: true
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
