class Screen < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  belongs_to :device

  has_many :ad_units
  # validations ...............................................................
  validates :uid, presence: true
  validates :operational_status, presence: true
  validates :orientation, inclusion: { in: %w[portrait landscape] }, allow_nil: true

  # callbacks .................................................................
  # scopes ....................................................................
  scope :active, -> { where(is_active: true) }
  scope :operational, -> { where(operational_status: "normal") }
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
