# frozen_string_literal: true

# == Schema Information
#
# Table name: sudos
#
#  id              :bigint           not null, primary key
#  email_address   :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_sudos_on_email_address  (email_address) UNIQUE
#
class Sudo < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  has_secure_password
  has_many :sessions, dependent: :destroy

  # validations ...............................................................
  normalizes :email_address, with: ->(e) { e.strip.downcase }

  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
